spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console is the path
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demoDB
  jpa:
    generate-ddl: false